/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Fourfours } from "./Fourfours";
export * as factories from "./factories";
export { Fourfours__factory } from "./factories/Fourfours__factory";
